repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        name: isort
        entry: isort --profile black
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
exclude: |
  (?x)^(
    pkg/apis/kubeflow.org/v1/openapi_generated.go|
    pkg/apis/kubeflow.org/v1/zz_.*|
    pkg/client/.*|
    test_job/apis/test_job/v1/.*generated.*.go|
    test_job/client/.*|
    docs/api/.*|
    hack/python-sdk/post_gen.py|
    sdk/python/kubeflow/training/[^/]*.py|
    sdk/python/kubeflow/training/models/.*|
    sdk/python/test/.*|
    sdk/python/docs/.*|
    sdk/python/.openapi-generator/VERSION|
    sdk/python/kubeflow/__init__.py|
  )$
