apiVersion: "kubeflow.org/v1"
kind: JAXJob
metadata:
  name: jaxjob-simple
  namespace: kubeflow
spec:
  jaxReplicaSpecs:
    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: jax
              image: ghcr.io/kubeflow/training-v1/jaxjob-simple:latest
              command:
                - "python3"
                - "train.py"
              imagePullPolicy: Always
