apiVersion: "kubeflow.org/v1"
kind: JAXJob
metadata:
  name: jaxjob-mnist
  namespace: kubeflow
spec:
  jaxReplicaSpecs:
    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: jax
              image: ghcr.io/kubeflow/training-v1/jaxjob-dist-spmd-mnist:latest
              imagePullPolicy: Always
