apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: elastic-example-echo
spec:
  elasticPolicy:
    rdzvBackend: c10d
    minReplicas: 1
    maxReplicas: 2
    maxRestarts: 100
  pytorchReplicaSpecs:
    Worker:
      replicas: 2
      template:
        spec:
          containers:
            - name: pytorch
              image: ghcr.io/kubeflow/training-v1/pytorch-elastic-example-echo:latest
              imagePullPolicy: IfNotPresent
              env:
              - name: LOGLEVEL
                value: DEBUG
              command:
                - python
                - -m
                - torch.distributed.run
                - --rdzv_backend=c10d
                - ./echo.py
